name: ESLint backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: ESLint Action eslintrc
        # You may pin to the exact commit or the version.
        # uses: mrdivyansh/eslint-action@17eb59b7430afff999b822cb161ef44e9bd7a1cd
        uses: mrdivyansh/eslint-action@v1.0.7
        with:
          # GitHub repository token for publishing inline lint annotations. Should be secrets.GITHUB_TOKEN.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Path to eslintrc
          eslint-rc: /backend/src
          # Root directory to lint files in
          execute-on-files: /backend/.eslintrc.json
